# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
"""Shared numeric defaults for Kaggle skill script entry points."""

DATE_PREVIEW_CHARS = 10

DEFAULT_DISCUSSION_MAX_PAGES = 5
DEFAULT_PAGE_SIZE = 20
DEFAULT_KERNEL_SCORE_PAGE_SIZE = 100

DEFAULT_QUERY_LIMIT = 50
DEFAULT_AUTHOR_COLUMN_WIDTH = 20
DEFAULT_REF_COLUMN_WIDTH = 55
DEFAULT_TITLE_COLUMN_WIDTH = 50

SECONDS_PER_MINUTE = 60
DEFAULT_POLL_INTERVAL_SECONDS = 30
DEFAULT_KERNEL_TIMEOUT_SECONDS = 86_400
OUTPUT_SEPARATOR_WIDTH = 50

MIN_DATASET_SLUG_LENGTH = 6
MAX_DATASET_SLUG_LENGTH = 50
